source:
  url: "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/historical/"
  station_meta_url: "https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/daily/kl/historical/KL_Tageswerte_Beschreibung_Stationen.txt"
  patterns:
    zip_pattern: 'href="(tageswerte_KL_.*?\.zip)"'
    product_pattern_to_extract: 'produkt_'
    header_keyword: 'STATIONS_ID'
    zip_glob: "*.zip"
    data_file_glob: "produkt_*.txt"
  file_properties:
    delimiter: ';'
    file_encoding: 'latin-1'
    na_value: -999
  paths:
    download_dir: "data"
    extract_dir: "data/unzipped"

database:
  type: "postgresql"
  host: "db"
  port: "5432"
  user: "user"
  password: "password"
  dbname: "wetter"
  sql_file_path: "Create_table.sql"
